on:
  push:
    branches:
      - master

jobs:
  test:
    uses: alexandermendes/workflows/workflows/test-js-package.yml

  release:
    needs: test
    uses: alexandermendes/workflows/workflows/release-js-package.yml
